# encoding: utf-8
"""This file includes necessary params, info."""
import mmcv

import os.path as osp
import numpy as np


K = np.array([[2481.9412514178307, 0.0, 978.95936559694314],
        [0.0, 2482.3917472975795, 629.72289542481894],
            [0.0, 0.0, 1.0]],dtype=np.float64)  

camera_matrix = K
width = 1920
height = 1200

cur_dir = osp.abspath(osp.dirname(__file__))
root_dir = osp.normpath("/mnt/data/work/synthetic-data-yolo-training_and_pose_estimation/src")

data_root = osp.join(root_dir, "output")
bop_root = osp.join(data_root, "bop")

# dataset_root = osp.join(bop_root, "mydataset")

train_dir = osp.join(bop_root, "train_pbr")
test_dir = osp.join(bop_root, "test_pbr")


id2obj = {
    1: "heart_shape",
    2: "semi_circle",
    3: "triangle_shape",
}
objects = list(id2obj.values())
obj2id = {v: k for k, v in id2obj.items()}
obj_num = len(id2obj)





# --- fields the EGL renderer / GDRN need ---
model_dir = osp.join(bop_root, "models")

texture_paths  = None          # your BlenderProc .ply models are untextured (vertex-colored), so None
vertex_scale   = 0.001         # models are in mm -> meters (matches scale_to_meter)
model_paths    = [osp.join(model_dir, "obj_{:06d}.ply".format(_id)) for _id in id2obj]
model_colors   = [((i + 1) * 5, (i + 1) * 5, (i + 1) * 5) for i in range(obj_num)]
model_eval_dir = osp.join(bop_root, "models")     # or a dedicated models_eval/ if you make one
zNear = 0.25
zFar  = 6.0
center = (height / 2, width / 2)
depth_factor = 1000.0




def get_models_info():
    """key is str(obj_id)"""
    models_info_path = osp.join(model_dir, "models_info.json")
    assert osp.exists(models_info_path), models_info_path
    models_info = mmcv.load(models_info_path)  # key is str(obj_id)
    return models_info

def get_fps_points():
    """key is str(obj_id) generated by
    core/gdrn_modeling/tools/hb/hb_1_compute_fps.py."""
    fps_points_path = osp.join(model_dir, "fps_points.pkl")
    try:
        assert osp.exists(fps_points_path), fps_points_path
    except AssertionError:
        import gdrnpp.core.gdrn_modeling.tools.hb.hb_1_compute_fps as compute_fps
        compute_fps.main()
        assert osp.exists(fps_points_path), fps_points_path
        
    fps_dict = mmcv.load(fps_points_path)
    print("Loaded FPS")
    print("="*80)

    for k,v in fps_dict.items():
        print(k)
        print(v["fps64_and_center"][:5])
        break

    print("="*80)
    return fps_dict


def get_keypoints_3d():
    """key is str(obj_id) generated by
    core/roi_pvnet/tools/hb/hb_1_compute_keypoints_3d.py."""
    keypoints_3d_path = osp.join(model_dir, "keypoints_3d.pkl")
    try:
        assert osp.exists(keypoints_3d_path), keypoints_3d_path
    except AssertionError:

        import gdrnpp.core.gdrn_modeling.tools.hb.hb_1_compute_keypoints_3d as compute_keypoints
        compute_keypoints.main()
        assert osp.exists(keypoints_3d_path), keypoints_3d_path
        
    kpts_dict = mmcv.load(keypoints_3d_path)
    return kpts_dict
